# example configuration file for rna-seq analysis
cluster:
  name: odyssey # arbitrary name
  profile: lsf2 # ipython profile to run under
  cores: 4 # number of ipython engines to spin up
  timeout: 10000 # time to wait for the cluster to be up before failing
  delay: 20 # the delay in spinning up engines once the controller is up

dir:
  results: results/human_mapping # results will go in this directory
  doc: doc # documentation for this analysis goes here
  ref: ref # reference files
  data: data # raw data goes here. make everything read only for safety
  meta: meta # metadata (annotation, etc) goes here

test_pipeline: False

log_dir: log

input_dir: test/data

ref: /n/hsphS10/hsphfs1/chb/biodata/genomes/Hsapiens/hg19/iGenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/Bowtie2Index/genome
gtf: /n/hsphS10/hsphfs1/chb/biodata/genomes/Hsapiens/hg19/iGenomes/Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf

annotation:
  name: hg19
  file: /n/hsphS10/hsphfs1/chb/biodata/genomes/Hsapiens/hg19/iGenomes/Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf


# this is the paths to the programs; if a Java library the path to where
# the jar file is kept
program:
  fastqc: fastqc
  tophat: tophat2
  bowtie: bowtie2
  picard: /n/HSPH/local/share/java/picard-1.79/

# configuration options for each stage of the analysis
stage:
  fastqc:
    name: fastqc
    program: fastqc
    options:
      - [--noextract]
      - [--threads, 4]

  cutadapt:
    program: cutadapt
    chemistry: [truseq]
    trim_polya: True
    options:
      error-rate: 0.1
      quality-cutoff: 20

  tophat:
    name: tophat
    program: tophat2
    options:
      b2-sensitive: True
    quality_format: sanger
    ref: /n/hsphS10/hsphfs1/chb/biodata/genomes/Hsapiens/hg19/iGenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/Bowtie2Index/genome
    gtf: /n/hsphS10/hsphfs1/chb/biodata/genomes/Hsapiens/hg19/iGenomes/Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf

  rnaseq_metrics:
    name: rnaseq_metrics
    program: picard
    ref:
      name: human
      file: /n/hsphS10/hsphfs1/chb/biodata/genomes/Hsapiens/hg19/iGenomes/Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/refFlat.txt
    ribo: meta/human_rrna.bed

  rseqc:
    name: rseqc

# order to run the stages in
run:
  [fastqc, cutadapt, fastqc, tophat, rnaseq_metrics, rseqc]
